AbstractGymMVC5/Controllers/AppointmentPersonsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AbstractGymMVC5.DAL;
using AbstractGymMVC5.Models;

namespace AbstractGymMVC5.Controllers
{
    public class AppointmentPersonsController : Controller
    {
        private AppointmentContext db = new AppointmentContext();

        // GET: AppointmentPersons
        public ActionResult Index()
        {
            return View(db.AppointmentPersons.ToList());
        }

        // GET: AppointmentPersons/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AppointmentPerson appointmentPerson = db.AppointmentPersons.Find(id);
            if (appointmentPerson == null)
            {
                return HttpNotFound();
            }
            return View(appointmentPerson);
        }

        // GET: AppointmentPersons/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: AppointmentPersons/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "FirstName,LastName")] AppointmentPerson appointmentPerson)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.AppointmentPersons.Add(appointmentPerson);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }

            }
            catch (DataException)
            {
                ModelState.AddModelError("", "We were unable to save changes. Please try again or contact the administrator.");
            }


            return View(appointmentPerson);
        }

        // GET: AppointmentPersons/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AppointmentPerson appointmentPerson = db.AppointmentPersons.Find(id);
            if (appointmentPerson == null)
            {
                return HttpNotFound();
            }
            return View(appointmentPerson);
        }

        // POST: AppointmentPersons/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,FirstName,LastName")] AppointmentPerson appointmentPerson)
        {
            if (ModelState.IsValid)
            {
                db.Entry(appointmentPerson).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(appointmentPerson);
        }

        // GET: AppointmentPersons/Delete/5
        public ActionResult Delete(int? id, bool? saveChangesError = false)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            if (saveChangesError.GetValueOrDefault())
            { 
                ViewBag.ErrorMessage = "Cannot delete. Try again or contact the administrator.";
            }

            AppointmentPerson appointmentPerson = db.AppointmentPersons.Find(id);
            if (appointmentPerson == null)
            {
                return HttpNotFound();
            }
            return View(appointmentPerson);
        }

        // POST: AppointmentPersons/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                AppointmentPerson appointmentPerson = db.AppointmentPersons.Find(id);
                db.AppointmentPersons.Remove(appointmentPerson);
                db.SaveChanges();
            }
            catch (DataException)
            {
                return RedirectToAction("Delete", new { id = id, saveChangesError = true });
            }

            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AbstractGymMVC5/Views/Shared/_Layout.cshtml
@using Microsoft.AspNet.Identity


<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Abstract Gym</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Abstract Gymnastics", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                   
                    @if (Request.IsAuthenticated) { 
                        <li>@Html.ActionLink("MyProfile", "MyProfile", "Home")</li>

                    }
                        <!--<li>@Html.ActionLink("Appointment with", "Index", "AppointmentPersons")</li>-->
                        <!--<li>@Html.ActionLink("Rooms", "Index", "Room")</li>-->
                    </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Abstract Gymnastics - 2017</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>